### PR TITLE
Getsidechaininfo fix

### PR DESCRIPTION
**Pull request by tomossomot**
Made a new branch and PR to not risk messing up rebase.

Ive added test for range of prefix values, PUBKEY_ADDRESS reconstruction of address and SCRIPT_ADDRESS reconstruction of address. Not sure if theres a way to test BLINDED_ADDRESS and SECRET_KEY?

### CODE REVIEW

**Comment by nkostoulas** [comment]
Rebase is fine as long as you haven't edited the same files with the latest changes in master. If you have then you need to carefully edit these, which is the same with merge anyway. In this case rebase should work instantly. Then you will need to force push your branch though because rebase will change the history. Merge on the other hand creates a commit that reapplies all the changes from master, which is a bit weird because you are committing them again. Usually neither are required but in this case it is due to the master test breaking.

**Comment by tomossomot** [comment]
Cheers, the problem though was laurence updating master after I had merged

**Comment by tomossomot** [comment]
I think i had trouble there because Laurence was changing things after I had merged. I see what you mean with force push now also.

**Comment by nkostoulas** [comment]
Yeah not sure what happened. I think you started from a branch that wasn't merged, then it got merged in master and you mixed both rebase and merge. 14 commits for a test addition is too much. Can you create a clean branch? Take some time to understand the merge/rebase difference, it's important.

**Pull request closed without merging**
