### PR TITLE
Guardnode: CLTV multisig transaction Solver/Signing and Request changes

### PR DESCRIPTION
**Pull request by nkostoulas**
- ported standard refactoring from bitcoin
https://github.com/bitcoin/bitcoin/pull/13194

- ported scripts_standard test
https://github.com/bitcoin/bitcoin/blob/master/src/test/script_standard_tests.cpp
I've commented stuff to do with witness refactoring and also bare multisig not being standard in bitcoin.

- new tx type TX_LOCKED_MULTISIG (#104)
- Solver handling for TX_LOCKED_MULTISIG (#104)
- sign handling for TX_LOCKED_MULTISIG (#104)
- end to end `requests.py` test: create raw request, fetch requests, spend previously locked request on expiry
- add Request class and FromSolutions constructor
- added Request list and add/remove/update on init and connect block

### CODE REVIEW

**Comment by nkostoulas** [comment]
Can you not squash so that the [backport] commits are evident! (Also I want to keep working on the same branch)

**Comment by nkostoulas** [comment]
@lawlawlaw any comments? Should I merge this?

**Comment by lawlawlaw** [comment]
Looking now...

**Comment by lawlawlaw** [comment]
Ok

**Pull request merged**
