### PR TITLE
try fix travis

### PR DESCRIPTION
**Pull request by nkostoulas**

### CODE REVIEW

**Comment by nkostoulas** [comment]
I don't get this genius build system. I included the two missing header files to `Makefile.am` and changes upper to lower case filenames per:
https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md
```
Use only the lowercase alphanumerics (a-z0-9), underscore (_) and hyphen (-) in source code filenames.

Rationale: grep:ing and auto-completing filenames is easier when using a consistent naming pattern. Potential problems when building on case-insensitive filesystems are avoided when using only lowercase characters in source code filenames.
```

Now 4/5 succeed and 5th fails with what seems to be a `policy.cpp` issue. 

Any thoughts @lawlawlaw @tomt1664 @lodenos @stakauskas

**Comment by lawlawlaw** [comment]
I don't get it. static const DEFAULT_MAX_MEMPOOL_SIZE is defined in policy.h at global scope, which is included in init.cpp. Yet the compiler complains that it wasn't declared in this scope.

**Comment by lawlawlaw** [comment]
Try ::DEFAULT_MAX_MEMPOOL_SIZE?

**Comment by nkostoulas** [comment]
That would have failed before. I don’t think we’ve changed anything on these files and the other builds still succeed. It might be related in some insane way to the addition of these new files but can’t really see how.

**Comment by nkostoulas** [comment]
fixed!

**Comment by lodenos** [comment]
@nkostoulas Nice, good job

**Pull request merged**
